import type { EngineLevel } from "@/types/engine";

/**
 * 8 difficulty levels.
 * Levels 1-6 use UCI_LimitStrength + UCI_Elo for strength targeting.
 * Levels 7-8 play at full strength with Skill Level only.
 * blunderChance adds random move injection to weaken lower levels
 * (Stockfish's UCI_Elo floor is ~1300 regardless of setting).
 */
export const ENGINE_LEVELS: readonly EngineLevel[] = [
  {
    level: 1,
    label: "Beginner",
    name: "Woody",
    skillLevel: 0,
    depth: 1,
    moveTimeMs: 50,
    artificialDelayMs: 800,
    elo: 400,
    limitStrength: true,
    blunderChance: 0.45,
    description: "Total novice",
    tagline: "I'm still learning the pieces!",
  },
  {
    level: 2,
    label: "Novice",
    name: "Luna",
    skillLevel: 1,
    depth: 1,
    moveTimeMs: 100,
    artificialDelayMs: 600,
    elo: 600,
    limitStrength: true,
    blunderChance: 0.3,
    description: "Casual learner",
    tagline: "Let's have a friendly game!",
  },
  {
    level: 3,
    label: "Amateur",
    name: "Felix",
    skillLevel: 3,
    depth: 2,
    moveTimeMs: 200,
    artificialDelayMs: 400,
    elo: 800,
    limitStrength: true,
    blunderChance: 0.15,
    description: "Knows the rules",
    tagline: "I know a few tricks now",
  },
  {
    level: 4,
    label: "Club Player",
    name: "Nadia",
    skillLevel: 5,
    depth: 4,
    moveTimeMs: 300,
    artificialDelayMs: 300,
    elo: 1000,
    limitStrength: true,
    blunderChance: 0.08,
    description: "Casual club",
    tagline: "Ready for a real challenge?",
  },
  {
    level: 5,
    label: "Intermediate",
    name: "Gareth",
    skillLevel: 8,
    depth: 6,
    moveTimeMs: 500,
    artificialDelayMs: 0,
    elo: 1200,
    limitStrength: true,
    blunderChance: 0,
    description: "Improving club",
    tagline: "I don't make many mistakes",
  },
  {
    level: 6,
    label: "Advanced",
    name: "Sable",
    skillLevel: 14,
    depth: 10,
    moveTimeMs: 750,
    artificialDelayMs: 0,
    elo: 1500,
    limitStrength: true,
    blunderChance: 0,
    description: "Competitive club",
    tagline: "Precision is my middle name",
  },
  {
    level: 7,
    label: "Expert",
    name: "Viktor",
    skillLevel: 17,
    depth: 14,
    moveTimeMs: 1000,
    artificialDelayMs: 0,
    elo: 1800,
    limitStrength: false,
    blunderChance: 0,
    description: "Tournament player",
    tagline: "Tournament-tested and battle-ready",
  },
  {
    level: 8,
    label: "Master",
    name: "Kassia",
    skillLevel: 20,
    depth: 20,
    moveTimeMs: 2000,
    artificialDelayMs: 0,
    elo: 2500,
    limitStrength: false,
    blunderChance: 0,
    description: "Expert/GM sparring",
    tagline: "No mercy.",
  },
] as const;

export const AI_ELO_MAP: ReadonlyMap<number, number> = new Map(
  ENGINE_LEVELS.map((l) => [l.level, l.elo]),
);

export const AI_NAME_MAP: ReadonlyMap<number, string> = new Map(
  ENGINE_LEVELS.map((l) => [l.level, l.name]),
);
